---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
# Please put your title here to include it in the file below.
Title <- "Efficient Estimation of Spatial Econometric Interaction Models for Sparse OD Matrices"
```

# Efficient Estimation of Spatial Econometric Interaction Models for Sparse OD Matrices

This repository contains all codes necessary to reproduce the results of our article *"`r Title`"*, currently available as a working paper:

> Dargel, Lukas, and Christine Thomas-Agnan (2023).
> *`r Title`*.
> TSE Working Paper, n.
> 23-1456, July 2023., Accessed `r format(Sys.Date(), "%d %b %Y")`.
> Online at <https://www.tse-fr.eu/sites/default/files/TSE/documents/doc/wp/2023/wp_tse_1409.pdf>

The article develops new calculation tools to efficiently estimate the gravity models that account for spatial dependence in OD flows.
A vignette accompanying the article presents the analysis of national level home-to-work commuting flows between the c.a. 35000 municipalities of metropolitan France and can be [downloaded directly as HTML](https://htmlpreview.github.io/?https://github.com/LukeCe/paper_Sparse_OD_Flows/blob/master/notebooks/%%%.html).

## Notes on reproducibility

To reproduce all results of the article and the vignette, you can run the bash commands below:

``` {.bash .sh}
# get all codes from GitHub
git clone https://github.com/LukeCe/paper_Sparse_OD_Flows
cd paper_Sparse_OD_Flows # change working directory to the cloned git

# build the docker image for the paper from the current directory
docker build -t repro_sparse_od_flows . 

# run the analysis from within the docker container
docker run --rm \
  -v .:/home/paper_Sparse_OD_Flows \  # mount the repository into the docker
  -w '/home/paper_Sparse_OD_Flows' \  # change working directory accordingly
  repro_sparse_od_flows \             # specfiy the docker image
  Rscript repro.R                     # execute the repro.R script
```

Executing the command `Rscript repro.R` performs the following steps:

1.  Download the three source data sets and places them in `in\data`:

    -   Election results [from the French Ministry of the Interior](https://www.data.gouv.fr/fr/datasets/election-presidentielle-des-10-et-24-avril-2022-resultats-definitifs-du-1er-tour/#/resources)
    -   Socio-demographic information from the population census [provided by INSEE](https://www.insee.fr/fr/statistiques/6543200)
    -   Geographic contours of French municipalities [provided by IGN](https://geoservices.ign.fr/adminexpress) (this file has about 250MB and can take some time to download)

2.  Merge the data sources and place the combined data in `out/data`

3.  Rebuild the HTML vignette that generates all results used in the article

    -   The vignette is placed in `notebooks`
    -   The outputs used for the article are placed in `out/figures` and `out/tables`

### How to cite

Please cite the above article when using any material from this repository.

### Licenses

**Text and figures :** [CC BY 4.0](http://creativecommons.org/licenses/by/4.0/)

**Code :** [GPL 3.0](https://www.gnu.org/licenses/gpl-3.0.en.html)

**Data :** See the policies of the original data providers
